### ISSUE TITLE
Bootstrap 4 Compatibility

### ISSUE THREAD

**Issue by sirhcybe** [valor-software/ng2-select#519]
I have an Angular 2 app with Bootstrap 4 and I'd like to use ng2-select. However, the button sizes use Bootstrap 3. I don't do much open source development so I'm not sure what the proper protocol is for this, but I'd be happy to do a PR or something with the upgrade.

**Comment by linusbrolin** [comment]
It is compatible with bootstrap 4, I'm using it for that myself.
However, it uses the default button size in bootstrap 4, with these css classes: `btn btn-secondary`.
In my pull request https://github.com/valor-software/ng2-select/pull/375 I have made all css optional (using @Input() variables), so that custom css classes can be used if wanted.
That way, you can make the button class smaller by using these bootstrap 4 classes instead: `btn btn-sm btn-secondary`.

However, my pull request has not been merged.
I'm going to update it to the current code base soon, and hope it will get merged then.

**Comment by sirhcybe** [comment]
While we wait for Bootstrap 4 compatibility, anyone who wants this library for the multi-select options can check out my fork here: https://github.com/sirhcybe/ng2-select-bootstrap4

Only the multi-select is working since that's all I needed and the need for this fork should go away eventually.

**Comment by optimistex** [comment]
Work by supporting Bootstrap 4 was planned: https://github.com/optimistex/ng2-select-ex/issues/5
@sirhcybe I'll take a look at your fork for figure out about ensure compatibility.

**Comment by umdstu** [comment]
@optimistex - I'm confused... you linked to a separate project. Are they related?

**Comment by optimistex** [comment]
@umdstu Of course, they are related.
My project is a fork from this project. I just continue contribution in my fork because this project is abandoned and have no more mantainers. Just check, the latest commit on this project from Nov 23, 2017

**Comment by sirhcybe** [comment]
Closing this issue since this repo is no longer maintained.
